### ISSUE TITLE
Game Logic VG (Select two out of four additional features)

### ISSUE THREAD

**Issue by cogmind** [cogmind/AnimalWorld#10]
- [x] Djur kan bli sjuka (20% chans per djur och spelrunda). I så fall måste man betala veterinärkostnader för dem (olika pris för olika slags djur). Då är det 50% chans att de blir friska. Annars dör de.
- [x] Man kan spara pågående spel till disk och fortsätta det senare. Flera spel kan sparas under olika filnamn. Användaren väljer filnamn.
- [ ] Man kan köpa och sälja djur till varandra (mellan olika spelare).
- [ ] Varje djurtyp har en maxålder och varje djur blir äldre för varje omgång. Åldern påverkar priset på djuret när man säljer det negativt. Ett djur som blivit äldre än sin maxålder dör.
