### ISSUE TITLE
More Game Logic

### ISSUE THREAD

**Issue by cogmind** [cogmind/AnimalWorld#8]
- [x] Djur har ett hälsovärde som från början är 100 procent. För varje spelomgång sjunker detta värde med 10 - 30 procentenheter (slumpa detta tal).
- [x] Om ett djur har hälsovärde 0 dör det. Meddela spelaren som äger djuret detta först i nästa runda.
- [x] Om man matar ett djur stiger dess hälsovärde - varje kg mat förbättrar djurets hälsa med 10 procent. (Om du vill får du lova att sätta olika djurs matbehov för att förbättra sin hälsa 10 procent till olika vikter av mat… Det kan ju vara rimligt att en mus behöver mindre mat än en elefant för att må bra?)
- [x] Ett viss typ av djur kan bara äta 1-3 av de sorters mat som finns i spelet. Att mata djuret med ett annat slags mat går inte. (Det får inte vara så att det finns ett slags mat som alla typer av djur kan äta.)
- [x] En spelare förlorar och lämnar spelet när spelaren inte har några pengar och inte har några djur.
- [x] Efter sista rundan säljs alla djur och spelaren får pengarna.
- [x] Den spelare som har mest pengar efter sista rundan vinner.
- [x] Se till att varje spelare tydligt i början av varje runda få information om vilka djur hen äger, vilken mat hen äger och hur mycket pengar hen har, samt hur mycket djurs hälsa har försämrats sedan förra omgången.
